# Generated by Django 3.2.6 on 2021-08-17 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Количество')),
                ('made', models.BooleanField(default=True, verbose_name='Выполнено')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('payed', models.IntegerField(default=0, verbose_name='Прибыль')),
                ('bill', models.IntegerField(default=0, verbose_name='Долг')),
                ('client_num', models.IntegerField(default=0, verbose_name='Количество клиентов')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Название')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('used_today', models.IntegerField(default=0, verbose_name='Использовано')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('isAdult', models.BooleanField(default=True, verbose_name='Взрослый')),
                ('payed', models.IntegerField(default=0, verbose_name='Оплачено')),
                ('bill', models.IntegerField(default=0, verbose_name='Долг')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.partner')),
            ],
        ),
    ]
